/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Feed
         * @description Every analysed article by default, newest first.
         *
         *     ``has_findings`` narrows the list in either direction and is left out entirely by
         *     default: a feed filtered to reported articles reads as a list of accusations, while
         *     measured precision under prompt v1.1.3 is 42% — more findings are wrong than right.
         *     Narrowing is available to a reader who asks for it and is never the view they are handed.
         */
        get: operations["read_feed_feed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{article_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Article
         * @description One article with the fragments reported in it.
         *
         *     404 also covers an article that exists but has never been analysed under the production
         *     configuration: there is nothing here to show a reader, and saying "no analysis yet"
         *     would invite a client to render an empty verdict as a clean bill of health.
         */
        get: operations["read_article_articles__article_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Deletes the row, not just the cookie. A cookie cleared in one browser while the
         *     session stays valid is exactly the gap server-side sessions exist to close.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/saved": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Saved */
        get: operations["list_saved_me_saved_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/saved/{article_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Save Article
         * @description PUT rather than POST: saving an article twice is the same as saving it once, and a
         *     reader double-tapping a bookmark should not get an error for it.
         */
        put: operations["save_article_me_saved__article_id__put"];
        post?: never;
        /** Unsave Article */
        delete: operations["unsave_article_me_saved__article_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Subscriptions */
        get: operations["list_subscriptions_me_subscriptions_get"];
        /**
         * Replace Subscriptions
         * @description The whole set at once. A settings screen sends what the person wants to end up with,
         *     and diffing it here costs one delete and one insert instead of a protocol.
         */
        put: operations["replace_subscriptions_me_subscriptions_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Account
         * @description A copy of the account, for Articles 15 and 20 GDPR.
         *
         *     JSON because the Regulation asks for a structured, commonly used, machine-readable
         *     format, and because the alternative — the operator running a query by hand for every
         *     request — is the arrangement that makes a deadline get missed.
         */
        get: operations["export_account_me_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Account
         * @description Erasure, not deactivation. Sessions go first so that a request in flight on another
         *     device cannot act on an account that is halfway gone.
         */
        delete: operations["delete_account_me_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ops/checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Integrity Checks
         * @description The same checks `make audit-data` runs, on the same definitions.
         *
         *     A query per iteration, which the project's rules otherwise forbid — but the loop is over
         *     five constants, not over rows, so it cannot grow with the data. Folding them into one
         *     UNION would mean assembling SQL from a tuple that carries its own parameters, which is
         *     more machinery than five round trips on an admin page are worth.
         */
        get: operations["integrity_checks_ops_checks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ops/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Overview
         * @description Everything the panel renders, in one round trip per section.
         *
         *     Untyped on purpose: these are counters read straight from SQL, and a Pydantic model per
         *     section would mean maintaining a schema whose only consumer is a table that prints it.
         */
        get: operations["overview_ops_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness for the container. Deliberately does not touch the database: a health check
         *     that fails on a slow query restarts a process that was working.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Account */
        Account: {
            /** Email */
            email: string;
            /** Role */
            role: string;
        };
        /** ArticleDetail */
        ArticleDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Lead */
            lead: string | null;
            /** Url */
            url: string;
            /** Source */
            source: string;
            /** Published At */
            published_at: string | null;
            category: components["schemas"]["Category"] | null;
            /** Category Confidence */
            category_confidence: number | null;
            overall_assessment: components["schemas"]["Assessment"] | null;
            /** Findings */
            findings: components["schemas"]["FindingOut"][];
            provenance: components["schemas"]["Provenance"];
        };
        /**
         * Assessment
         * @description Overall verdict for one article.
         * @enum {string}
         */
        Assessment: "neutral" | "mildly_loaded" | "heavily_loaded";
        /**
         * Category
         * @description Fixed topical taxonomy.
         *
         *     ``INNE`` ("other") is the escape hatch, added to the seven topical categories. Without
         *     one the model forces every article into the nearest category, which quietly corrupts
         *     the feed.
         *
         *     **The values are Polish because they are the wire format, not identifiers for a
         *     reader.** The system prompt is Polish and names these eight words as the permitted
         *     answers, so this is what the model emits and what the CHECK constraint accepts. No
         *     reader ever sees them: ``web/messages/`` maps each to a display name in both locales.
         *
         *     They are nonetheless inconsistent with ``ManipulationType``, whose values are English
         *     and come out of the same prompt — an artefact of the taxonomies having different
         *     origins, not a decision. **Migrating them to English is intended**, and it is not a
         *     rename: the prompt has to change, which bumps ``PROMPT_VERSION`` and makes every
         *     published quality figure describe a configuration nobody has measured. It therefore
         *     belongs with the next evaluation run, alongside a migration for the CHECK constraint
         *     and the stored rows — never on its own.
         * @enum {string}
         */
        Category: "polityka" | "kultura" | "technologia" | "sport" | "biznes" | "geopolityka" | "zdrowie" | "inne";
        /** Check */
        Check: {
            /** Name */
            name: string;
            /** Why */
            why: string;
            /** Failures */
            failures: number;
            /** Passing */
            passing: boolean;
        };
        /** Credentials */
        Credentials: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Password
             * Format: password
             */
            password: string;
        };
        /**
         * Export
         * @description Everything stored about one account, in one object.
         *
         *     Sessions are described, never disclosed: the table holds SHA-256 digests of tokens, and
         *     a token is a live credential. Their timestamps answer "what do you know about my
         *     sign-ins"; the digests would answer nothing and hand a downloaded file the power to
         *     impersonate. The password hash is left out for the same reason.
         */
        Export: {
            /** Email */
            email: string;
            /**
             * Account Created At
             * Format: date-time
             */
            account_created_at: string;
            /** Sessions */
            sessions: {
                [key: string]: string;
            }[];
            /** Saved Articles */
            saved_articles: components["schemas"]["FeedItem"][];
            /** Subscriptions */
            subscriptions: components["schemas"]["Category"][];
        };
        /** Feed */
        Feed: {
            /** Items */
            items: components["schemas"]["FeedItem"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** FeedItem */
        FeedItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Lead */
            lead: string | null;
            /** Url */
            url: string;
            /** Source */
            source: string;
            /** Published At */
            published_at: string | null;
            category: components["schemas"]["Category"] | null;
            overall_assessment: components["schemas"]["Assessment"] | null;
            /** Finding Count */
            finding_count: number;
        };
        /**
         * FindingOut
         * @description One reported fragment.
         *
         *     ``start``/``end`` index the original ``field`` string, so a client slices rather than
         *     searches. That is the property the quote validator exists to guarantee and the reason
         *     its tests slice the source string instead of comparing text.
         */
        FindingOut: {
            type: components["schemas"]["ManipulationType"];
            /**
             * Field
             * @enum {string}
             */
            field: "title" | "lead";
            /** Quote */
            quote: string;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Explanation */
            explanation: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Neutral Alternative */
            neutral_alternative: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ManipulationType
         * @description Closed vocabulary of language techniques the model may report.
         *
         *     The list is closed on purpose. An open-ended "find manipulation" instruction produces
         *     a different taxonomy on every call, which cannot be measured, compared across models,
         *     or defended to the outlet being described.
         *
         *     ``clickbait_hook`` looks like the weakest of the six, and **deleting it has already
         *     been tried and reverted**. Filtering it out of stored results suggested precision would
         *     rise from 46% to 49%; prompt v1.3.0, which actually removed it from the taxonomy,
         *     measured 40%. The model does not stop noticing those headlines when the label goes away
         *     — it files them under ``emotional_load``, where they count as false positives just the
         *     same. Removing a type offline is not the same experiment as removing it from the prompt.
         * @enum {string}
         */
        ManipulationType: "emotional_load" | "fear_appeal" | "overgeneralization" | "loaded_question" | "unsourced_figure" | "clickbait_hook";
        /**
         * Provenance
         * @description Where the analysis came from, carried alongside it rather than beside it.
         *
         *     Article 50 of Regulation (EU) 2024/1689 requires generated content to be disclosed as
         *     generated. What travels here is the fact, not the sentence: a client that renders an
         *     analysis cannot avoid receiving ``ai_generated``, while the wording it shows is a
         *     translated string and belongs with the other translated strings.
         */
        Provenance: {
            /**
             * Ai Generated
             * @default true
             * @constant
             */
            ai_generated: true;
            /**
             * Human Verified
             * @default false
             * @constant
             */
            human_verified: false;
            /** Model Name */
            model_name: string;
            /** Prompt Version */
            prompt_version: string;
            /**
             * Analysed At
             * Format: date-time
             */
            analysed_at: string;
        };
        /**
         * SignIn
         * @description Sign-in does not repeat the length rule: an old password shorter than today's floor
         *     must still get its owner in, and rejecting it here would leak the rule to a guesser.
         */
        SignIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Password
             * Format: password
             */
            password: string;
        };
        /** Subscriptions */
        Subscriptions: {
            /** Categories */
            categories: components["schemas"]["Category"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_feed_feed_get: {
        parameters: {
            query?: {
                category?: components["schemas"]["Category"] | null;
                has_findings?: boolean | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feed"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_article_articles__article_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
        };
    };
    list_saved_me_saved_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedItem"][];
                };
            };
        };
    };
    save_article_me_saved__article_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unsave_article_me_saved__article_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_subscriptions_me_subscriptions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscriptions"];
                };
            };
        };
    };
    replace_subscriptions_me_subscriptions_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Subscriptions"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscriptions"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_account_me_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Export"];
                };
            };
        };
    };
    delete_account_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    integrity_checks_ops_checks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Check"][];
                };
            };
        };
    };
    overview_ops_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
